### ISSUE TITLE
Open Mobile CV 4.9.0

### ISSUE THREAD

**Issue by PJ5168** [Fishwaldo/sophgo-sg200x-debian#11]
Dear Sir,

Not sure if this is image v1.3.0 related or not. 
Following the instructions on Milk V web site, download the Mobile OpenCV 4.9.0 and build locally on Duo 256.
The output of resized image is correct. 
However, there are some messages shown during the execution of compiled cpp code as following:

debian@duo256:~/opencv/build$ ls -l
total 3092
-rw-rw-r-- 1 debian debian   14209 May 25 08:09 CMakeCache.txt
drwxrwxr-x 6 debian debian    4096 May 25 08:10 CMakeFiles
-rw-rw-r-- 1 debian debian    5082 May 25 08:09 Makefile
-rw-rw-r-- 1 debian debian    1614 May 25 08:09 cmake_install.cmake
-rw-rw-r-- 1 debian debian  320103 May 25 08:13 in.jpg
-rw-rw-r-- 1 debian debian   21178 May 25 08:53 out.jpg
-rwxrwxr-x 1 debian debian 2784568 May 25 08:10 resize.o

debian@duo256:~/opencv/build$ time ./resize.o
opencv-mobile HW JPG decoder with cvi
/mnt/system/lib/libsys.so: cannot open shared object file: No such file or directory
/mnt/system/lib/libsys.so: cannot open shared object file: No such file or directory
/mnt/system/lib/libawb.so: cannot open shared object file: No such file or directory

real    0m0.334s
user    0m0.262s
sys     0m0.068s
debian@duo256:~/opencv/build$

Thank you!

**Comment by Fishwaldo** [comment]
None of the Camera/Video etc subsystem has been ported over due to MilkV only releasing binary libraries that are only compatible with the Buildroot image they release.

**Comment by PJ5168** [comment]
Roger that. Thanks!

**Comment by PJ5168** [comment]
Installed the normal OpenCV 4.6.0 instead.

**Comment by PJ5168** [comment]
Tested the dnn_superres of cv2 4.6.0 by python 3.11.9. 
It's working but a little bit slow. On Duo S, the EDSR test used 448MB of RAM.
