### ISSUE TITLE
Not able to flash emmc

### ISSUE THREAD

**Issue by rohanringe** [Fishwaldo/sophgo-sg200x-debian#13]
I downloaded duos-emmc.zip file and tried to flash duo s but giving below error

D:\CviBurn_v2.0_cli_windows>.\usb_dl.exe -s linux -c cv181x -i .\rom
[INFO] Using libusb v1.0.26.11724
[INFO] Waiting for USB device connection: ---
[INFO] found usb device vid=0x3346 pid=0x1000
[INFO] USB download start...

[INFO] Waiting for USB device connection:  /
[INFO] found usb device vid=0x3346 pid=0x1000
[INFO] set MGN1 flag
[INFO] break
[INFO] Connecting to ROM 2nd stage...
[INFO] Waiting for USB device connection:  |
[INFO] found usb device vid=0x3346 pid=0x1000
[INFO] fip_tx_offset: 0, fip_tx_size: 4096
[INFO] set MGN1 flag
[INFO] break

[INFO] Waiting for USB device connection:  |
[INFO] found usb device vid=0x3346 pid=0x1000
[INFO] fip_tx_offset: 4096, fip_tx_size: 33280
[INFO] set MGN1 flag
[INFO] break

[INFO] Waiting for USB device connection:  /
[INFO] found usb device vid=0x3346 pid=0x1000
[INFO] fip_tx_offset: 37376, fip_tx_size: 4096
[INFO] set MGN1 flag
[INFO] break

[INFO] Waiting for USB device connection:  |
[INFO] found usb device vid=0x3346 pid=0x1000
[INFO] Waiting for USB device connection:  /
[INFO] found usb device vid=0x3346 pid=0x1000
[INFO] fip_tx_offset: 41472, fip_tx_size: 8192
[INFO] set MGN1 flag
[INFO] break

[INFO] Waiting for USB device connection: ---
[INFO] found usb device vid=0x3346 pid=0x1000
[INFO] fip_tx_offset: 49664, fip_tx_size: 512
[INFO] set MGN1 flag
[INFO] break

[INFO] Waiting for USB device connection:  |
[INFO] found usb device vid=0x3346 pid=0x1000
[INFO] fip_tx_offset: 50176, fip_tx_size: 110592
[INFO] set MGN1 flag
[INFO] break

[INFO] Waiting for USB device connection:  |
[INFO] found usb device vid=0x3346 pid=0x1000
[INFO] fip_tx_offset: 160768, fip_tx_size: 512
[INFO] set MGN1 flag
[INFO] break

[INFO] Waiting for USB device connection:  |
[INFO] found usb device vid=0x3346 pid=0x1000
[INFO] fip_tx_offset: 160768, fip_tx_size: 244224
[INFO] set MGN1 flag
[INFO] break

[INFO] usb device not foundce connection: ---

Please help

**Comment by Fishwaldo** [comment]
Please use release 1.4
