### ISSUE TITLE
how to detect UVC camera

### ISSUE THREAD

**Issue by Ccccraz** [Fishwaldo/sophgo-sg200x-debian#16]
device: LicheeRV nano

dear all

I want to read video from a UVC camera, and I have already set the USB of my LicheeRV Nano to host mode. What should I do to make the LicheeRV Nano recognize my UVC camera?

**Comment by Fishwaldo** [comment]
As noted in the readme - none of of the video/camera support has been ported to this image. (Due to some closed source binary files that are not compatible with glibc used in Debian. You have to stay with the Buildroot image to use any Camera function)

**Comment by Fishwaldo** [comment]
That's fine!

**Comment by bhupiister** [comment]
is there any progress in supporting USB cameras on the debian image?
