### ISSUE TITLE
Can't build emmc image

### ISSUE THREAD

**Issue by ModFol** [Fishwaldo/sophgo-sg200x-debian#20]
Hello,

I tried to build the emmc image using your instructions. The first time I run it I get an error message that the 'image' directory does not exist. I created two directories, image and configs before running again. I now get the following output:

Trying to pull ghcr.io/fishwaldo/sophgo-sg200x-debian:master...
Getting image source signatures
Copying blob 2149717ebf5b done  
Copying blob 2e84f4c11671 done  
Copying blob a79fdf356ad4 done  
Copying blob ee3bdca30f89 done  
Copying config 08a8dcc977 done  
Writing manifest to image destination
Storing signatures
Makefile:21: *** Board duos not supported.  Stop.

**Comment by Fishwaldo** [comment]
You have to run from the directory where you checked out the repository
