### ISSUE TITLE
What is the default password for the root account?

### ISSUE THREAD

**Issue by Doraemonsan** [Fishwaldo/sophgo-sg200x-debian#26]
Hi guys, could someone tell me the default root password? I flashed licheervnano_sd.img (v1.4.0) and it's running well, successfully obtaining a network address via DHCP. However, I'm having trouble logging in via SSH using the root account. I've tried several passwords like password, root, admin, 000000, but none seem to work.

**Comment by Fishwaldo** [comment]
Per Debian standard configuration - logging in with root via SSH is disabled. You have to login as a normal user and use su/sudo to root. 

This is documented in the readme: https://github.com/Fishwaldo/sophgo-sg200x-debian?tab=readme-ov-file#image-info

**Comment by Doraemonsan** [comment]
> 根据 Debian 标准配置 - 禁用通过 SSH 使用 root 身份登录。您必须以普通用户身份登录并使用 su/sudo 获得 root 身份。
> 
> 这在自述文件中有记录：[https://github.com/Fishwaldo/sophgo-sg200x-debian ?tab=readme-ov-file#image-info](https://github.com/Fishwaldo/sophgo-sg200x-debian?tab=readme-ov-file#image-info)
Thank you, I didn't read it carefully
