### ISSUE TITLE
USB WiFi

### ISSUE THREAD

**Issue by PJ5168** [Fishwaldo/sophgo-sg200x-debian#7]
Dear Sir,

Really appreciate your builds.
I have both Duo-256 and LicheeRV nano WiFi.
I use "systemctl disable usb-gadget-rndis" to turn off the RNDIS.
Then "lsusb" can see all the USB devices attached to Duo-256 w/ IO board as following : 

debian@duo256:~$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 001 Device 004: ID 0406:620b Fujitsu-ICL Computers USB Composite Device
Bus 001 Device 005: ID 05ac:1502 Apple, Inc. USB DISK
Bus 001 Device 006: ID 148f:7601 Ralink Technology, Corp. MT7601U Wireless Adapter

There are three USB devices attached, they are MSC, HID, and WiFi class devices.
However, none of them are functioning.
Tried to install related kernel drivers but no help.
Could you please advise how to proceed next?

Best Regards,

**Comment by PJ5168** [comment]
debian@duo256:~$ dmesg | grep usb
[    0.229248] usbcore: registered new interface driver usbfs
[    0.235197] usbcore: registered new interface driver hub
[    0.240792] usbcore: registered new device driver usb
[    0.750635] dwc2 4340000.usb: axi clk installed
[    0.755415] dwc2 4340000.usb: apb clk installed
[    0.760133] dwc2 4340000.usb: 125m clk installed
[    0.764936] dwc2 4340000.usb: 33k clk installed
[    0.769646] dwc2 4340000.usb: 12m clk installed
[    0.774436] dwc2 4340000.usb: EPs: 8, dedicated fifos, 3072 entries in SPRAM
[    0.782239] dwc2 4340000.usb: DWC OTG Controller
[    0.787101] dwc2 4340000.usb: new USB bus registered, assigned bus number 1
[    0.794362] dwc2 4340000.usb: irq 34, io mem 0x04340000
[    0.956503] usbcore: registered new interface driver usbhid
[    0.962348] usbhid: USB HID core driver
[    1.207891] usb 1-1: new high-speed USB device number 2 using dwc2
[    1.727016] usb 1-1.1: new high-speed USB device number 3 using dwc2
[    1.837173] usb 1-1.1: config 1 has an invalid descriptor of length 0, skipping remainder of the config
[    1.848030] usb 1-1.1: config 1 interface 0 altsetting 0 endpoint 0x7 has invalid wMaxPacketSize 0
[    1.857841] usb 1-1.1: config 1 interface 0 altsetting 0 bulk endpoint 0x7 has invalid maxpacket 0
[    1.867560] usb 1-1.1: config 1 interface 0 altsetting 0 has 7 endpoint descriptors, different from the interface descriptor's value: 8
[    2.092278] usb 1-1.3: new full-speed USB device number 4 using dwc2
[    2.206909] input: XING WEI 2.4G USB USB Composite Device as /devices/platform/4340000.usb/usb1/1-1/1-1.3/1-1.3:1.2/0003:0406:620B.0001/input/input0
[    2.223523] hid-generic 0003:0406:620B.0001: input: USB HID v1.10 Keyboard [XING WEI 2.4G USB USB Composite Device] on usb-4340000.usb-1.3/input2
[    2.243037] input: XING WEI 2.4G USB USB Composite Device Mouse as /devices/platform/4340000.usb/usb1/1-1/1-1.3/1-1.3:1.3/0003:0406:620B.0002/input/input1
[    2.259653] input: XING WEI 2.4G USB USB Composite Device Consumer Control as /devices/platform/4340000.usb/usb1/1-1/1-1.3/1-1.3:1.3/0003:0406:620B.0002/input/input2
[    2.275578] input: XING WEI 2.4G USB USB Composite Device System Control as /devices/platform/4340000.usb/usb1/1-1/1-1.3/1-1.3:1.3/0003:0406:620B.0002/input/input3
[    2.292165] hid-generic 0003:0406:620B.0002: input: USB HID v1.10 Mouse [XING WEI 2.4G USB USB Composite Device] on usb-4340000.usb-1.3/input3
[    2.392281] usb 1-1.4: new high-speed USB device number 5 using dwc2

**Comment by Fishwaldo** [comment]
Can you post the output of dmesg after plugging in the WiFi adapter?

**Comment by PJ5168** [comment]
debian@duo256:~$ [  155.501822] usb 1-1.1: USB disconnect, device number 3
[  157.771161] usb 1-1.1: new high-speed USB device number 6 using dwc2

**Comment by PJ5168** [comment]
[    2.392281] usb 1-1.4: new high-speed USB device number 5 using dwc2
[  155.501822] usb 1-1.1: USB disconnect, device number 3
[  157.771161] usb 1-1.1: new high-speed USB device number 6 using dwc2

**Comment by Fishwaldo** [comment]
It looks like it is working fine (it's some sort of keyboard/mouse etc?). What were you expecting?

**Comment by PJ5168** [comment]
Would like to use USB wifi.
The HID and MSC are for testing only.

**Comment by PJ5168** [comment]
Tried four different USB WiFi, but no luck.

**Comment by Fishwaldo** [comment]
Do a lsmod and see if the driver loaded. If not I would need to check the kernel config to see if we build a driver for that model.

**Comment by PJ5168** [comment]
debian@duo256:~$ lsmod
Module                  Size  Used by
cvitek_remoteproc       9898  0
rtc_cvitek              4496  1
adc_cvitek             11438  0
pwm_cvitek              6275  0
cvitek_mailbox          8898  0
input_leds              3615  0

**Comment by Fishwaldo** [comment]
I will look into it later but if you want to do something now, this is the kernel config for the Duo256: https://github.com/Fishwaldo/sophgo-sg200x-debian/blob/master/configs/duo256/linux/defconfig

If you can find the right CONFIG_ option, you can add it to that file and rebuild the image yoursel using the instruction in the readme.

**Comment by PJ5168** [comment]
Four USB WiFi tested are :
1. MT7601U
2. RTL8723BU
3. MT7610U(Asus AC51)
4. 802.11AC, ID : 0bda:c820

**Comment by PJ5168** [comment]
# CONFIG_USB_NET_DRIVERS is not set
# CONFIG_WLAN_VENDOR_ADMTEK is not set
# CONFIG_WLAN_VENDOR_MEDIATEK is not set
# CONFIG_WLAN_VENDOR_RALINK is not set

**Comment by Fishwaldo** [comment]
There are CONFIG_ options available that are not listed in that file. I suspect some for individual drivers from each vendor. So you need to do some research

**Comment by Fishwaldo** [comment]
I've added a bunch of USB Wifi Drivers to the kernel config. You can grab a test image from the actions artifact page, or wait till the next release.

**Comment by PJ5168** [comment]
Dear Sir,

Thanks for the update. Tested on the v1.3.0 image on Duo256 with IO base board. The USB WiFi is pluged into the USB A port.
After disable the rndis, can see the USB devices on the hub.
Tested on couple USB WiFi cards, Seems that all the drivers were loaded with same error code -2. Therefore, no link is available.
Please advise. Thanks!

Best Regards,

PJ.

-----------------------------------------------------------------
debian@duo256:~$ lsmod
Module                  Size  Used by
mt7601u                74007  0
mac80211              532400  1 mt7601u
cfg80211              364636  2 mt7601u,mac80211
libarc4                 1524  1 mac80211
cvitek_remoteproc      11332  0
rtc_cvitek              4402  1
adc_cvitek             12797  0
pwm_cvitek              7233  0
cvitek_mailbox         10362  0

debian@duo256:~$ dmesg | grep mt7601u
[   14.778579] mt7601u 1-1.1:1.0: ASIC revision: 76010001 MAC revision: 76010500
[   14.800710] mt7601u 1-1.1:1.0: Direct firmware load for mt7601u.bin failed with error -2
[   14.825168] mt7601u: probe of 1-1.1:1.0 failed with error -2
[   14.831223] usbcore: registered new interface driver mt7601u
debian@duo256:~$

**Comment by PJ5168** [comment]
debian@duo256:~$ dmesg | grep mt7601u
[   14.478607] mt7601u 1-1.1:1.0: ASIC revision: 76010001 MAC revision: 76010500
[   14.500464] mt7601u 1-1.1:1.0: Direct firmware load for mt7601u.bin failed with error -2
[   14.523926] mt7601u: probe of 1-1.1:1.0 failed with error -2
[   14.529978] usbcore: registered new interface driver mt7601u
debian@duo256:~$

**Comment by Fishwaldo** [comment]
you need to install the firmware package:
```
apt install firmware-linux
```
 (or possibly firmware-linux-nonfree)

**Comment by PJ5168** [comment]
Dear Sir,

My bad, forget to install them for 1.3 image. After installed related packages. The driver is loaded without error code -2.

debian@duo256:~$ lsmod
Module                  Size  Used by
mt7601u                74007  0
mac80211              532400  1 mt7601u
cfg80211               364636  2 mt7601u,mac80211
libarc4                   1524  1 mac80211

debian@duo256:~$ dmesg | grep mt7601u
[   14.626302] mt7601u 1-1.3:1.0: ASIC revision: 76010001 MAC revision: 76010500
[   14.700549] mt7601u 1-1.3:1.0: EEPROM ver:0c fae:00
[   14.973969] usbcore: registered new interface driver mt7601u
[   15.120182] mt7601u 1-1.3:1.0 wlxe0b94d179709: renamed from wlan0

However, the wifi interface becomes 'unmanaged."
Therefore, edit the /etc/NetworkManager/NetworkManager.conf file, then add "[ifupdown] managed=true"
The wifi interface become "unavailable." 

Use "nmtui" add wifi connection but can not activate it. 
But the radio --> wifi hardware : enabled Software: enabled

The "ip link set up" no help.
ip link list output:
4: wlxe0b94d179709: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether f6:50:89:9a:f9:56 brd ff:ff:ff:ff:ff:ff permaddr e0:b9:4d:17:97:09

And the nmcli shows it is unavailable.
debian@duo256:~$ sudo nmcli dev status
DEVICE                     TYPE           STATE                             CONNECTION
end0                         ethernet     connected                     Wired connection 1
lo                              loopback    connected (externally)  lo
wlxe0b94d179709    wifi             unavailable                    --
tunl0                         iptunnel     unmanaged                   --

Try "sudo dhclient" has no effect.
The "sudo nmcli dev wifi" scan no AP available.

Please advise. Appreciate!

**Comment by PJ5168** [comment]
debian@duo256:~$ nmcli general status
STATE         CONNECTIVITY  WIFI-HW  WIFI        WWAN-HW  WWAN     METERED
connected  full                      enabled   enabled  missing         enabled    no (guessed)

debian@duo256:~$ sudo iwconfig
lo        no wireless extensions.
end0      no wireless extensions.
tunl0     no wireless extensions.
wlxa036bc87b0fb  no wireless extensions.
wlxe0b94d179709  no wireless extensions.
wlx90de8069be6f  no wireless extensions.

debian@duo256:~$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 001 Device 003: ID 0bda:b720 Realtek Semiconductor Corp. RTL8723BU 802.11b/g/n WLAN Adapter
Bus 001 Device 004: ID 0b05:17d1 ASUSTek Computer, Inc. AC51 802.11a/b/g/n/ac Wireless Adapter [Mediatek MT7610U]
Bus 001 Device 007: ID 0bda:c820 Realtek Semiconductor Corp. 802.11ac NIC
Bus 001 Device 009: ID 148f:7601 Ralink Technology, Corp. MT7601U Wireless Adapter

debian@duo256:~$ sudo ip link list
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: end0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether fe:18:0d:47:20:1a brd ff:ff:ff:ff:ff:ff
    altname enxfe180d47201a
3: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: wlxa036bc87b0fb: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether a0:36:bc:87:b0:fb brd ff:ff:ff:ff:ff:ff
5: wlxe0b94d179709: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether e0:b9:4d:17:97:09 brd ff:ff:ff:ff:ff:ff
6: wlx90de8069be6f: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether 90:de:80:69:be:6f brd ff:ff:ff:ff:ff:ff

**Comment by PJ5168** [comment]
Seems that the RDNIS can not be removed? Still enabled?

debian@duo256:~$ sudo systemctl list-unit-files --state=enabled
UNIT FILE                          STATE   PRESET
avahi-daemon.service               enabled enabled
cron.service                       enabled enabled
e2scrub_reap.service               enabled enabled
getty@.service                     enabled enabled
networking.service                 enabled enabled
NetworkManager-dispatcher.service  enabled enabled
NetworkManager-wait-online.service enabled enabled
NetworkManager.service             enabled enabled
ssh.service                        enabled enabled
systemd-pstore.service             enabled enabled
systemd-timesyncd.service          enabled enabled
usb-gadget-rndis-usb0.service      enabled enabled
avahi-daemon.socket                enabled enabled
remote-fs.target                   enabled enabled
apt-daily-upgrade.timer            enabled enabled
apt-daily.timer                    enabled enabled
dpkg-db-backup.timer               enabled enabled
e2scrub_all.timer                  enabled enabled
fstrim.timer                       enabled enabled
logrotate.timer                    enabled enabled

**Comment by Fishwaldo** [comment]
> usb-gadget-rndis-usb0.service

That's an ancillary service that's only activated when the actual usb0 network interface appears. (It starts up dnsmasq etc for DHCP service) 

You only need to worry about usb-gadget-rndis.service.

**Comment by Fishwaldo** [comment]
I can't really help with your wireless cards as I don't have them. You will have to troubleshoot yourself.

**Comment by PJ5168** [comment]
Thanks for the help these days.
After installing related packages, the USB WiFi is working now.
Really appreciate!
