### ISSUE TITLE
Readme :  Add line  enable usb switch 

### ISSUE THREAD

**Issue by bolloplayer** [Fishwaldo/sophgo-sg200x-debian#8]
There is also a option to start a serial port (ACM) interface **(for the use of the USB-A port)**  instead of the rndis interface, to do this, you can run the following command:

systemctl disable usb-gadget-rndis
systemctl enable usb-gadget-acm

After disabling the usg-gadget-* service, you need to enable the usb-switch (if your connecting to the TypeA port):

systemctl enable usb-switch

After executing these commands, you need to reboot.

**Comment by F-Fichter** [comment]
root@licheervnano:~# systemctl enable usb-switch
Failed to enable unit: Unit file usb-switch.service does not exist.

**Comment by Fishwaldo** [comment]
> root@licheervnano:~# systemctl enable usb-switch Failed to enable unit: Unit file usb-switch.service does not exist.

usb-switch is only needed on DuoS. There is no USB Hub on the licheervnano, so just disabling the usb-gadget is all that is required (after rebooting)

**Comment by Fishwaldo** [comment]
Updated Readme. Thanks
