### ISSUE TITLE
no keyboard via uart

### ISSUE THREAD

**Issue by F-Fichter** [Fishwaldo/sophgo-sg200x-debian#9]
hello,

 i haven't keyboard in 2 last img.  

i use a arduino for ttyusb0 work fine with other, and linux debian : screen /dev/ttyUSB0 115200

I see all, boot etc, but no keyboard, ok rndis is ok  :)

**nice img, i have a lot of usb matérial 👍🏽** 

debian@licheervnano:~$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 003: ID 0d8c:0014 C-Media Electronics, Inc. Audio Adapter (Unitek Y-247A)
Bus 001 Device 004: ID 05e3:0745 Genesys Logic, Inc. Logilink CR0012
Bus 001 Device 006: ID 12d1:1c2b Huawei Technologies Co., Ltd. AIRBOX

have a good day

**Comment by Fishwaldo** [comment]
Nothing to do with the image. Check your connections.
